/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/low-poly_city_asset_pack_v1.0.glb -o src/models.js -k -K -r public 
Author: BUKKBEEK (https://sketchfab.com/bukkbeek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-asset-pack-v10-ab2105dc5b5648d7a867479a55f3c254
Title: Low-poly city asset pack v1.0
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/low-poly_city_asset_pack_v1.0.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="07611176e3934778af4bcc712cd135c4fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Camera" position={[380.7, 395.371, 1732.181]} rotation={[-3.142, 1.14, 2.904]} scale={100}>
                <group name="Object_4" />
              </group>
              <group name="Area" position={[-1233.003, 1021.124, -590.814]} scale={4822.897}>
                <group name="Object_6" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_7" />
                </group>
              </group>
              <group name="House_5" position={[498.656, -1.345, 202.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_5_Material_0" geometry={nodes.House_5_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_4" position={[498.656, -1.345, 502.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_4_Material_0" geometry={nodes.House_4_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_3" position={[498.656, -1.345, 802.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_3_Material_0" geometry={nodes.House_3_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_2" position={[498.656, -1.345, 1102.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_2_Material_0" geometry={nodes.House_2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_1" position={[498.656, -1.345, 1402.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_1_Material_0" geometry={nodes.House_1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_10" position={[798.656, -1.345, 202.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_10_Material_0" geometry={nodes.House_10_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_9" position={[798.656, -1.345, 502.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_9_Material_0" geometry={nodes.House_9_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_8" position={[798.656, -1.345, 802.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_8_Material_0" geometry={nodes.House_8_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_7" position={[798.656, -1.345, 1102.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_7_Material_0" geometry={nodes.House_7_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="House_6" position={[798.656, -1.345, 1402.336]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="House_6_Material_0" geometry={nodes.House_6_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree2" position={[1167.079, 0, -511.88]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree2_Material_0" geometry={nodes.Pine_tree2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree1" position={[957.673, 0, -511.88]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree1_Material_0" geometry={nodes.Pine_tree1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree_snow" position={[1090.347, 0, -1659.981]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree_snow_Material_0" geometry={nodes.Pine_tree_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cube_Tree1" position={[800, 0, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={[26.864, 26.864, 116.513]}>
                <mesh name="Cube_Tree1_Material_0" geometry={nodes.Cube_Tree1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Tree2" position={[1069.553, 0, -1428.631]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.752, 18.752, 81.328]}>
                <mesh name="Tree2_Material_0" geometry={nodes.Tree2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Tree_snow" position={[1090.347, 0, -1917.029]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.752, 18.752, 81.328]}>
                <mesh name="Tree_snow_Material_0" geometry={nodes.Tree_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Green_bush" position={[1054.384, 0, -41.407]} rotation={[-1.979, 0.898, 0.895]} scale={[23.363, 30.693, 23.489]}>
                <mesh name="Green_bush_Material_0" geometry={nodes.Green_bush_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Green_bush_snow" position={[1210.336, 0, -41.407]} rotation={[-1.979, 0.898, 0.895]} scale={[23.363, 30.693, 23.489]}>
                <mesh name="Green_bush_snow_Material_0" geometry={nodes.Green_bush_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Tree1" position={[1090.344, 0, -1152.153]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.752, 18.752, 81.328]}>
                <mesh name="Tree1_Material_0" geometry={nodes.Tree1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Yellow_bush" position={[1054.384, 0, -197.358]} rotation={[-1.979, 0.898, 0.895]} scale={[23.363, 30.693, 23.489]}>
                <mesh name="Yellow_bush_Material_0" geometry={nodes.Yellow_bush_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Yellow_bush_snow" position={[1210.336, 0, -197.358]} rotation={[-1.979, 0.898, 0.895]} scale={[23.363, 30.693, 23.489]}>
                <mesh name="Yellow_bush_snow_Material_0" geometry={nodes.Yellow_bush_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cube_Tree2" position={[500, 0, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={[26.864, 26.864, 116.513]}>
                <mesh name="Cube_Tree2_Material_0" geometry={nodes.Cube_Tree2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree3" position={[757.673, 0, -511.88]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree3_Material_0" geometry={nodes.Pine_tree3_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree4" position={[557.673, 0, -511.88]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree4_Material_0" geometry={nodes.Pine_tree4_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Pine_tree5" position={[557.673, 0, -711.88]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[16.224, 16.224, 121.622]}>
                <mesh name="Pine_tree5_Material_0" geometry={nodes.Pine_tree5_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence" position={[1300, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_Material_0" geometry={nodes.Fence_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Rock" position={[1400, 0, 0]} rotation={[-Math.PI / 2, 0, 0.716]} scale={[59.234, 59.234, 90.57]}>
                <mesh name="Rock_Material_0" geometry={nodes.Rock_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller1" position={[1460.64, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller1_Material_0" geometry={nodes.Fence_piller1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller2" position={[1552.061, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller2_Material_0" geometry={nodes.Fence_piller2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Mudrock" position={[1600, 0, 0]} rotation={[-Math.PI / 2, 0, 0.716]} scale={[59.234, 59.234, 90.57]}>
                <mesh name="Mudrock_Material_0" geometry={nodes.Mudrock_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Rock_snow" position={[1400, 0, -200]} rotation={[-Math.PI / 2, 0, 0.716]} scale={[59.234, 59.234, 90.57]}>
                <mesh name="Rock_snow_Material_0" geometry={nodes.Rock_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Mudrock_snow" position={[1600, 0, -200]} rotation={[-Math.PI / 2, 0, 0.716]} scale={[59.234, 59.234, 90.57]}>
                <mesh name="Mudrock_snow_Material_0" geometry={nodes.Mudrock_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller3" position={[1660.64, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller3_Material_0" geometry={nodes.Fence_piller3_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller4" position={[1752.061, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller4_Material_0" geometry={nodes.Fence_piller4_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_plank" position={[1100, 0, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_plank_Material_0" geometry={nodes.Fence_plank_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_snow" position={[1300, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_snow_Material_0" geometry={nodes.Fence_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller1_snow" position={[1460.64, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller1_snow_Material_0" geometry={nodes.Fence_piller1_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller2_snow" position={[1552.061, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller2_snow_Material_0" geometry={nodes.Fence_piller2_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller3_snow" position={[1660.64, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller3_snow_Material_0" geometry={nodes.Fence_piller3_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Fence_piller4_snow" position={[1752.061, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={[-18.423, 21.264, 63.918]}>
                <mesh name="Fence_piller4_snow_Material_0" geometry={nodes.Fence_piller4_snow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Helipad" position={[863.193, 0, -947.466]} rotation={[-Math.PI / 2, 0, 0]} scale={139.554}>
                <mesh name="Helipad_Material_0" geometry={nodes.Helipad_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_base" position={[100, 0, 1700]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="River_base_Material_0" geometry={nodes.River_base_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_flow" position={[100, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="River_flow_Material_0" geometry={nodes.River_flow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_flow_expand" position={[100, 0, 1100]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="River_flow_expand_Material_0" geometry={nodes.River_flow_expand_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_flow_X" position={[100, 0, 800]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
                <mesh name="River_flow_X_Material_0" geometry={nodes.River_flow_X_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_flow_T" position={[100, 0, 500]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                <mesh name="River_flow_T_Material_0" geometry={nodes.River_flow_T_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="River_flow_L" position={[100, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="River_flow_L_Material_0" geometry={nodes.River_flow_L_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_tar" position={[50, 0, -350]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_tar_Material_0" geometry={nodes.Road_tar_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_tar_L" position={[50, 0, -950]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                <mesh name="Road_tar_L_Material_0" geometry={nodes.Road_tar_L_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_tar_T" position={[50, 0, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_tar_T_Material_0" geometry={nodes.Road_tar_T_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_tar_X" position={[50, 0, -650]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_tar_X_Material_0" geometry={nodes.Road_tar_X_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_soil" position={[-250, 0, -350]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_soil_Material_0" geometry={nodes.Road_soil_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_soil_L" position={[-250, 0, -950]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                <mesh name="Road_soil_L_Material_0" geometry={nodes.Road_soil_L_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_soil_T" position={[-250, 0, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_soil_T_Material_0" geometry={nodes.Road_soil_T_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_soil_X" position={[-250, 0, -650]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_soil_X_Material_0" geometry={nodes.Road_soil_X_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_grass" position={[-550, 0, -350]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_grass_Material_0" geometry={nodes.Road_grass_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_grass_L" position={[-550, 0, -950]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                <mesh name="Road_grass_L_Material_0" geometry={nodes.Road_grass_L_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_grass_T" position={[-550, 0, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_grass_T_Material_0" geometry={nodes.Road_grass_T_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Road_grass_X" position={[-550, 0, -650]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Road_grass_X_Material_0" geometry={nodes.Road_grass_X_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Billboard1" position={[300, 0, -1000]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[18.158, 18.158, 41.786]}>
                <mesh name="Billboard1_Material_0" geometry={nodes.Billboard1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lamp_tower" position={[300, 0, -500]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[18.158, 18.158, 41.786]}>
                <mesh name="Lamp_tower_Material_0" geometry={nodes.Lamp_tower_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Billboard2" position={[300, 0, -900]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[18.158, 18.158, 41.786]}>
                <mesh name="Billboard2_Material_0" geometry={nodes.Billboard2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Billboard3" position={[300, 0, -800]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[18.158, 18.158, 41.786]}>
                <mesh name="Billboard3_Material_0" geometry={nodes.Billboard3_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Billboard4" position={[300, 0, -700]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[18.158, 18.158, 41.786]}>
                <mesh name="Billboard4_Material_0" geometry={nodes.Billboard4_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Waterpump" position={[300, 0, -600]} rotation={[-Math.PI / 2, 0, 0]} scale={22.491}>
                <mesh name="Waterpump_Material_0" geometry={nodes.Waterpump_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Traffic_light" position={[300, 0, -300]} rotation={[-Math.PI / 2, 0, 0]} scale={20.399}>
                <mesh name="Traffic_light_Material_0" geometry={nodes.Traffic_light_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="ATM" position={[300, 0, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.884, 37.563, 37.563]}>
                <mesh name="ATM_Material_0" geometry={nodes.ATM_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Dust_bin" position={[300, 0, -200]} rotation={[-Math.PI / 2, 0, 0]} scale={16.885}>
                <mesh name="Dust_bin_Material_0" geometry={nodes.Dust_bin_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bridge" position={[550, 100, -1050]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.463, 100, 9.463]}>
                <mesh name="Bridge_Material_0" geometry={nodes.Bridge_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_soil" position={[-200, 0, 1700]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_soil_Material_0" geometry={nodes['2_Cube_soil_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_sand" position={[-200, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_sand_Material_0" geometry={nodes['2_Cube_sand_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_grass" position={[-200, 0, 1100]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_grass_Material_0" geometry={nodes['2_Cube_grass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_yellowgrass" position={[-200, 0, 800]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_yellowgrass_Material_0" geometry={nodes['2_Cube_yellowgrass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_rock" position={[-200, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_rock_Material_0" geometry={nodes['2_Cube_rock_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Cube_snow" position={[-200, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Cube_snow_Material_0" geometry={nodes['2_Cube_snow_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_soil" position={[-500, 0, 1700]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_soil_Material_0" geometry={nodes['2_Plane_soil_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_sand" position={[-500, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_sand_Material_0" geometry={nodes['2_Plane_sand_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_grass" position={[-500, 0, 1100]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_grass_Material_0" geometry={nodes['2_Plane_grass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_yellowgrass" position={[-500, 0, 800]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_yellowgrass_Material_0" geometry={nodes['2_Plane_yellowgrass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_rock" position={[-500, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_rock_Material_0" geometry={nodes['2_Plane_rock_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2_Plane_snow" position={[-500, 0, 200]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2_Plane_snow_Material_0" geometry={nodes['2_Plane_snow_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_soil" position={[-1000, 0, 1650]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_soil_Material_0" geometry={nodes['4_Cube_soil_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_sand" position={[-1000, 0, 1150]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_sand_Material_0" geometry={nodes['4_Cube_sand_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_grass" position={[-1000, 0, 650]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_grass_Material_0" geometry={nodes['4_Cube_grass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_yellowgrass" position={[-1000, 0, 150]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_yellowgrass_Material_0" geometry={nodes['4_Cube_yellowgrass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_rock" position={[-1000, 0, -350]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_rock_Material_0" geometry={nodes['4_Cube_rock_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Cube_snow" position={[-1000, 0, -850]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Cube_snow_Material_0" geometry={nodes['4_Cube_snow_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_soil" position={[-1500, 0, 1650]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_soil_Material_0" geometry={nodes['4_Plane_soil_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_sand" position={[-1500, 0, 1150]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_sand_Material_0" geometry={nodes['4_Plane_sand_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_grass" position={[-1500, 0, 650]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_grass_Material_0" geometry={nodes['4_Plane_grass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_yellowgrass" position={[-1500, 0, 150]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_yellowgrass_Material_0" geometry={nodes['4_Plane_yellowgrass_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_rock" position={[-1500, 0, -350]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_rock_Material_0" geometry={nodes['4_Plane_rock_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="4_Plane_snow" position={[-1500, 0, -850]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 200, 100]}>
                <mesh name="4_Plane_snow_Material_0" geometry={nodes['4_Plane_snow_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="Car_Blue" position={[1200, 0, 1000]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Blue_Material_0" geometry={nodes.Car_Blue_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Car_Red" position={[1300, 0, 1000]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Red_Material_0" geometry={nodes.Car_Red_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Car_Green" position={[1400, 0, 1000]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Green_Material_0" geometry={nodes.Car_Green_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Car_Black" position={[1500, 0, 1000]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Black_Material_0" geometry={nodes.Car_Black_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Blue" position={[1200, 0, 1200]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Blue_Material_0" geometry={nodes.Jeep_Blue_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Car_Yellow" position={[1600, 0, 1000]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Yellow_Material_0" geometry={nodes.Car_Yellow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Red" position={[1300, 0, 1200]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Red_Material_0" geometry={nodes.Jeep_Red_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Green" position={[1400, 0, 1200]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Green_Material_0" geometry={nodes.Jeep_Green_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Black" position={[1500, 0, 1200]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Black_Material_0" geometry={nodes.Jeep_Black_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Yellow" position={[1600, 0, 1200]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Yellow_Material_0" geometry={nodes.Jeep_Yellow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cab_Blue" position={[1200, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Cab_Blue_Material_0" geometry={nodes.Cab_Blue_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cab_Red" position={[1300, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Cab_Red_Material_0" geometry={nodes.Cab_Red_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cab_Green" position={[1400, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Cab_Green_Material_0" geometry={nodes.Cab_Green_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cab_Black" position={[1500, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Cab_Black_Material_0" geometry={nodes.Cab_Black_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cab_Yellow" position={[1600, 0, 1400]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Cab_Yellow_Material_0" geometry={nodes.Cab_Yellow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bus_Blue" position={[1200, 0, 767.455]} rotation={[-Math.PI / 2, 0, 0]} scale={[39.552, 94.333, 43.294]}>
                <mesh name="Bus_Blue_Material_0" geometry={nodes.Bus_Blue_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lorry_Blue" position={[1200, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={[43.294, 94.333, 43.294]}>
                <mesh name="Lorry_Blue_Material_0" geometry={nodes.Lorry_Blue_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bus_Red" position={[1300, 0, 767.455]} rotation={[-Math.PI / 2, 0, 0]} scale={[39.552, 94.333, 43.294]}>
                <mesh name="Bus_Red_Material_0" geometry={nodes.Bus_Red_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bus_Green" position={[1400, 0, 767.455]} rotation={[-Math.PI / 2, 0, 0]} scale={[39.552, 94.333, 43.294]}>
                <mesh name="Bus_Green_Material_0" geometry={nodes.Bus_Green_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bus_Black" position={[1500, 0, 767.455]} rotation={[-Math.PI / 2, 0, 0]} scale={[39.552, 94.333, 43.294]}>
                <mesh name="Bus_Black_Material_0" geometry={nodes.Bus_Black_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Bus_Yellow" position={[1600, 0, 767.455]} rotation={[-Math.PI / 2, 0, 0]} scale={[39.552, 94.333, 43.294]}>
                <mesh name="Bus_Yellow_Material_0" geometry={nodes.Bus_Yellow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lorry_Red" position={[1300, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={[43.294, 94.333, 43.294]}>
                <mesh name="Lorry_Red_Material_0" geometry={nodes.Lorry_Red_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lorry_Green" position={[1400, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={[43.294, 94.333, 43.294]}>
                <mesh name="Lorry_Green_Material_0" geometry={nodes.Lorry_Green_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lorry_Black" position={[1500, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={[43.294, 94.333, 43.294]}>
                <mesh name="Lorry_Black_Material_0" geometry={nodes.Lorry_Black_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Lorry_Yellow" position={[1600, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={[43.294, 94.333, 43.294]}>
                <mesh name="Lorry_Yellow_Material_0" geometry={nodes.Lorry_Yellow_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Car_Police" position={[1200, 0, 1600]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Car_Police_Material_0" geometry={nodes.Car_Police_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Jeep_Police" position={[1600, 0, 1600]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.826, 61.994, 32.826]}>
                <mesh name="Jeep_Police_Material_0" geometry={nodes.Jeep_Police_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Helicopter" position={[1400, 0, 1600]} rotation={[-Math.PI / 2, 0, 0]} scale={35.285}>
                <mesh name="Helicopter_Material_0" geometry={nodes.Helicopter_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building17" position={[-1300, 0, -1500]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 200, 100]}>
                <mesh name="Building17_Material_0" geometry={nodes.Building17_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building1" position={[-400, 0, -1300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building1_Material_0" geometry={nodes.Building1_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building6" position={[-400, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building6_Material_0" geometry={nodes.Building6_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building2" position={[-100, 0, -1300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building2_Material_0" geometry={nodes.Building2_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building7" position={[-100, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building7_Material_0" geometry={nodes.Building7_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building3" position={[200, 0, -1300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building3_Material_0" geometry={nodes.Building3_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building8" position={[200, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building8_Material_0" geometry={nodes.Building8_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building4" position={[500, 0, -1300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building4_Material_0" geometry={nodes.Building4_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building9" position={[500, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building9_Material_0" geometry={nodes.Building9_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building5" position={[800, 0, -1300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building5_Material_0" geometry={nodes.Building5_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building10" position={[800, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building10_Material_0" geometry={nodes.Building10_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building11" position={[-400, 0, -1900]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building11_Material_0" geometry={nodes.Building11_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building12" position={[-100, 0, -1900]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building12_Material_0" geometry={nodes.Building12_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building13" position={[200, 0, -1900]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building13_Material_0" geometry={nodes.Building13_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building14" position={[500, 0, -1900]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building14_Material_0" geometry={nodes.Building14_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Building16" position={[800, 0, -1900]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building16_Material_0" geometry={nodes.Building16_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="2x2_building" position={[-700, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2x2_building_Material_0" geometry={nodes['2x2_building_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2x2_base" position={[-700, 0, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="2x2_base_Material_0" geometry={nodes['2x2_base_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2x4_building" position={[-1000, 0, -1500]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 200, 100]}>
                <mesh name="2x4_building_Material_0" geometry={nodes['2x4_building_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="2x4_base" position={[-1000, 0, -1500]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 200, 100]}>
                <mesh name="2x4_base_Material_0" geometry={nodes['2x4_base_Material_0'].geometry} material={materials.Material} />
              </group>
              <group name="Building15" position={[-1600, 0, -1500]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 200, 100]}>
                <mesh name="Building15_Material_0" geometry={nodes.Building15_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Plane" rotation={[-Math.PI / 2, 0, 0]} scale={[1886.016, 2148.037, 2638.158]}>
                <mesh name="Plane_Material_0" geometry={nodes.Plane_Material_0.geometry} material={materials.Material} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low-poly_city_asset_pack_v1.0.glb')
